// <auto-generated />
using System;
using System.Text.Json;
using MessengerWebhook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MessengerWebhook.Data.Migrations
{
    [DbContext(typeof(MessengerBotDbContext))]
    [Migration("20260417081447_AddDraftOrderCommercialConfirmationFlags")]
    partial class AddDraftOrderCommercialConfirmationFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessengerWebhook.Data.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.BotConversationLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<Guid?>("HumanSupportCaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UnlockAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPSID", "IsLocked");

                    b.ToTable("BotConversationLocks");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Color", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ABTestVariant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("AdditionalMetrics")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConversationOutcome")
                        .HasColumnType("text");

                    b.Property<int>("ConversationTurn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedEmotion")
                        .HasColumnType("text");

                    b.Property<decimal?>("EmotionConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JourneyStage")
                        .HasColumnType("text");

                    b.Property<string>("MatchedTone")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PipelineLatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ValidationErrors")
                        .HasColumnType("jsonb");

                    b.Property<bool?>("ValidationPassed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ABTestVariant");

                    b.HasIndex("ConversationOutcome")
                        .HasFilter("conversation_outcome IS NOT NULL");

                    b.HasIndex("MessageTimestamp");

                    b.HasIndex("SessionId");

                    b.HasIndex("TenantId");

                    b.ToTable("ConversationMetrics");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ABTestVariant")
                        .HasColumnType("text");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SurveySent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ABTestVariant");

                    b.HasIndex("FacebookPSID")
                        .IsUnique();

                    b.HasIndex("FacebookPageId");

                    b.HasIndex("LastActivityAt");

                    b.ToTable("ConversationSessions");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ABTestVariant")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookPsid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ABTestVariant");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Rating");

                    b.HasIndex("SessionId");

                    b.HasIndex("TenantId");

                    b.ToTable("ConversationSurveys");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.CustomerIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<int>("FailedDeliveries")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LifetimeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulDeliveries")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPSID")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("TenantId");

                    b.ToTable("CustomerIdentities");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.DraftOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedManagerEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("InventoryConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSubmissionAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSubmissionError")
                        .HasColumnType("text");

                    b.Property<decimal>("MerchandiseTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NobitaOrderId")
                        .HasColumnType("text");

                    b.Property<bool>("PriceConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PromotionConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByEmail")
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RiskSummary")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShippingConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedByEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerIdentityId");

                    b.HasIndex("DraftCode")
                        .IsUnique();

                    b.HasIndex("FacebookPageId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("DraftOrders");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.DraftOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DraftOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("GiftCode")
                        .HasColumnType("text");

                    b.Property<string>("GiftName")
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DraftOrderId");

                    b.ToTable("DraftOrderItems");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.FacebookPageConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppSecretOverride")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultManagerEmail")
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryPage")
                        .HasColumnType("boolean");

                    b.Property<string>("PageAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifyToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPageId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("FacebookPageConfigs");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.HumanSupportCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedByEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DraftOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("FacebookPSID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPageId")
                        .HasColumnType("text");

                    b.Property<string>("LastNotificationError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastNotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByEmail")
                        .HasColumnType("text");

                    b.Property<bool>("ResumeBotOnNextMessage")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TranscriptExcerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPSID");

                    b.HasIndex("FacebookPageId");

                    b.HasIndex("Status");

                    b.ToTable("HumanSupportCases");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.IngredientCompatibility", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ingredient1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredient2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ingredient1", "Ingredient2");

                    b.ToTable("IngredientCompatibilities");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.KnowledgeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsPublished");

                    b.ToTable("KnowledgeSnapshots");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ManagerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacebookPageConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FacebookPageConfigId");

                    b.HasIndex("TenantId");

                    b.ToTable("ManagerProfiles");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContraindicationsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NobitaLastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NobitaProductId")
                        .HasColumnType("integer");

                    b.Property<string>("NobitaSyncError")
                        .HasColumnType("text");

                    b.Property<decimal>("NobitaWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SkinConcernsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SkinTypesJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texture")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("pH")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique();

                    b.ToTable("ProductEmbeddings");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductGiftMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GiftCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GiftCode");

                    b.HasIndex("ProductCode");

                    b.HasIndex("TenantId", "ProductCode", "GiftCode")
                        .IsUnique();

                    b.ToTable("ProductGiftMappings");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VariantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductVariant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SizeId")
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VolumeML")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SizeId");

                    b.HasIndex("ProductId", "VolumeML", "Texture")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.RiskSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DraftOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerIdentityId");

                    b.HasIndex("DraftOrderId");

                    b.HasIndex("Level");

                    b.ToTable("RiskSignals");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Size", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.SkinProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcernsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensitivitiesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SkinProfiles");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.VipProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("GreetingStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastOrderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LifetimeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerIdentityId")
                        .IsUnique();

                    b.ToTable("VipProfiles");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Cart", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.CartItem", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerWebhook.Data.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationMessage", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationMetric", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerWebhook.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ConversationSurvey", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.CustomerIdentity", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.DraftOrder", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.CustomerIdentity", "CustomerIdentity")
                        .WithMany()
                        .HasForeignKey("CustomerIdentityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessengerWebhook.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("CustomerIdentity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.DraftOrderItem", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.DraftOrder", "DraftOrder")
                        .WithMany("Items")
                        .HasForeignKey("DraftOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftOrder");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.FacebookPageConfig", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Tenant", "Tenant")
                        .WithMany("FacebookPages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ManagerProfile", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.FacebookPageConfig", "FacebookPageConfig")
                        .WithMany()
                        .HasForeignKey("FacebookPageConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessengerWebhook.Data.Entities.Tenant", "Tenant")
                        .WithMany("Managers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FacebookPageConfig");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Order", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerWebhook.Data.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductEmbedding", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Product", "Product")
                        .WithOne()
                        .HasForeignKey("MessengerWebhook.Data.Entities.ProductEmbedding", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductGiftMapping", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Gift", "Gift")
                        .WithMany("ProductGiftMappings")
                        .HasForeignKey("GiftCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerWebhook.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.ProductVariant", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.Color", null)
                        .WithMany("Variants")
                        .HasForeignKey("ColorId");

                    b.HasOne("MessengerWebhook.Data.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerWebhook.Data.Entities.Size", null)
                        .WithMany("Variants")
                        .HasForeignKey("SizeId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.RiskSignal", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.CustomerIdentity", "CustomerIdentity")
                        .WithMany("RiskSignals")
                        .HasForeignKey("CustomerIdentityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MessengerWebhook.Data.Entities.DraftOrder", "DraftOrder")
                        .WithMany("RiskSignals")
                        .HasForeignKey("DraftOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CustomerIdentity");

                    b.Navigation("DraftOrder");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.SkinProfile", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.ConversationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.VipProfile", b =>
                {
                    b.HasOne("MessengerWebhook.Data.Entities.CustomerIdentity", "CustomerIdentity")
                        .WithOne("VipProfile")
                        .HasForeignKey("MessengerWebhook.Data.Entities.VipProfile", "CustomerIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerIdentity");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Color", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.CustomerIdentity", b =>
                {
                    b.Navigation("RiskSignals");

                    b.Navigation("VipProfile");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.DraftOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RiskSignals");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Gift", b =>
                {
                    b.Navigation("ProductGiftMappings");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Size", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MessengerWebhook.Data.Entities.Tenant", b =>
                {
                    b.Navigation("FacebookPages");

                    b.Navigation("Managers");
                });
#pragma warning restore 612, 618
        }
    }
}
